# Установить дефолт-ждк и мавен на сборочный хост
# Склонировать с гита репо и собрать джава приложение, получив артефакт на сборочном хосте 
# Установить томкат на продакшен хост 
# Скопировать артефакт на продакшен хост
---
- name: Install Maven and Git
  hosts: build-host
  become: yes

  tasks:
  - name: Ensure OpenJDK is present
    apt:
     name: default-jdk
     state: present
     update_cache: yes

  - name: Ensure Maven is present
    apt:
     name: maven
     state: present
     
  - name: Ensure Git is present
    apt:
     name: git
     state: present

- name: Build Java app 
  hosts: build-host
  become: yes

  tasks:
  - name: Clone Java app from GitHub
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
     clone: yes
     dest: /tmp/boxfuse-sample-java-war-hello
  
  - name: Build Java app
    shell: mvn package
    args:
     chdir: /tmp/boxfuse-sample-java-war-hello
  
- name: Install Tomcat
  hosts: production-host
  become: yes

  tasks: 
  - name: Ensure OpenJDK is present
    apt:
     name: default-jdk
     state: present
     update_cache: yes

  - name: Ensure tomcat is present
    apt:
     name: tomcat9
     state: present

  - name: Ensure tomcat service is running
    service:
     name: tomcat9
     state: started
  
- name: Deploy Java artefact
  hosts: production-host
  become: yes
  
  tasks:
  - name: Copy war file to production-host
    synchronize:
     src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
     dest: /var/lib/tomcat9/webapps/hello-1.0.war
    delegate_to: host2
  