# Установить дефолт-ждк и мавен на сборочный хост
# Склонировать с гита репо и собрать джава приложение, получив артефакт на сборочном хосте 
# Установить томкат на продакшен хост 
# Скопировать артефакт на продакшен хост
---
- name: Install Maven and Git
  hosts: build-host
  become: yes

  tasks:
  - name: Ensure OpenJDK is present
    apt:
     name: default-jdk
     state: present
     update_cache: yes

  - name: Ensure Maven is present
    apt:
     name: maven
     state: present
     
  - name: Ensure Git is present
    apt:
     name: git
     state: present

- name: Build Java app 
  hosts: build-host
  become: yes

  tasks:
  - name: Clone Java app from GitHub
    git:
     repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
     clone: yes
     dest: /tmp/boxfuse-sample-java-war-hello
  
  - name: Build Java app
    shell: mvn package
    args:
     chdir: /tmp/boxfuse-sample-java-war-hello
  
- name: Install Tomcat
  hosts: production-host
  become: yes

  tasks:
  - name: Ensure wget is present
    apt:
     name: wget
     state: present
     update_cache: yes

  - name: Download Tomcat 9
    shell: 